### ISSUE TITLE
关于天行api

### ISSUE THREAD

**Issue by adzcsx2** [rxrw/autojs-dingtalk#3]
第一次用天行，
天行api是否是https://www.tianapi.com/console/
里面的数据管理-我的密钥key
是否需要申请接口
我直接拿到那个密钥key，复制到config里面去，显示"TYPE ERROR can't read property 0 from xxxxx main.js#314"

**Comment by rxrw** [comment]
curl http://api.tianapi.com/txapi/jiejiari/index?key=你的key&date=2021-12-12 ，看看报什么错。

**Comment by adzcsx2** [comment]
明白了要申请工作日的接口才能用
