### ISSUE TITLE
如何保持autojs进程持续执行???

### ISSUE THREAD

**Issue by Allen-LPL** [rxrw/autojs-dingtalk#4]
首先感谢大佬的分享.

我想问一下项目是如何保持进程的自启动的? 使用tasker么?

之所以有这个疑问, 是因为我在测试启用的时候, 只是弹出了"不用打卡"就结束了.

**Comment by rxrw** [comment]
弹出不用打卡，因为没有到你设定的上下班时间。

我之前没有找到autojs直接接口提供的定时任务，使用的是蚂蚁森林那位大佬代码中提供的设定定时任务的函数。

目前的代码，在设定好后，不用打卡会设定好下一次打卡时间，配置了bark则会发送bark通知。

**Comment by Allen-LPL** [comment]
再次感谢大佬的分享.

那我今天用测试机测试一下看看
